apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: numberone-homolog

resources:
  - ../../base
  - namespace.yaml

labels:
  - pairs:
      environment: homolog
      tags.datadoghq.com/env: homolog
      tags.datadoghq.com/service: numberone-auto-service-api
    includeSelectors: false
    includeTemplates: true

patches:
  - path: configmap-patch.yaml
