apiVersion: v1
kind: Service
metadata:
  name: numberone-api-service
  labels:
    app.kubernetes.io/name: numberone-auto-service-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: numberone-auto-service-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
