apiVersion: v1
kind: ServiceAccount
metadata:
  name: numberone-api
  labels:
    app.kubernetes.io/name: numberone-auto-service-api
    app.kubernetes.io/component: api
automountServiceAccountToken: false
